---

name: re-dependency-review

on:  # yamllint disable-line rule:truthy
  workflow_call:

permissions:
  contents: read

jobs:
  review: # https://github.com/actions/dependency-review-action
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Pull Request Dependency Review
      uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 # 4.8.2
      with:
        license-check: false
        vulnerability-check: true
        show-openssf-scorecard: false
        fail-on-severity: low
